//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAccione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tAccione()
        {
            this.tPerfilAcciones = new HashSet<tPerfilAccione>();
        }
    
        public int idAcciones { get; set; }
        public string Accion { get; set; }
        public short Ajax { get; set; }
        public short MenuPadre { get; set; }
        public short MenuHijo { get; set; }
        public string Icono { get; set; }
        public Nullable<short> Estatus { get; set; }
        public int idControl { get; set; }
        public string Descripcion { get; set; }
    
        public virtual tControle tControle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPerfilAccione> tPerfilAcciones { get; set; }
    }
}
