//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tActividadVendedore
    {
        public int idActividad { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<short> TipoReporte { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Comentarios { get; set; }
        public Nullable<short> Estatus { get; set; }
    
        public virtual tUsuario tUsuario { get; set; }
    }
}
