//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tBitacoraProductosInventario
    {
        public int idBitacoraProductoInventario { get; set; }
        public Nullable<int> idInventario { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual tInventario tInventario { get; set; }
        public virtual tProducto tProducto { get; set; }
    }
}
