//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCarrito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tCarrito()
        {
            this.tDetalleCarritoes = new HashSet<tDetalleCarrito>();
            this.tRespaldoVentasEnLineas = new HashSet<tRespaldoVentasEnLinea>();
            this.tRespaldoVentasEnLineas1 = new HashSet<tRespaldoVentasEnLinea>();
            this.tVentasEnLineas = new HashSet<tVentasEnLinea>();
        }
    
        public int idCarrito { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> CantidadProductos { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Estatus { get; set; }
    
        public virtual tClientesTiendaVirtual tClientesTiendaVirtual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleCarrito> tDetalleCarritoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRespaldoVentasEnLinea> tRespaldoVentasEnLineas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRespaldoVentasEnLinea> tRespaldoVentasEnLineas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tVentasEnLinea> tVentasEnLineas { get; set; }
    }
}
