//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCatalogoVista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tCatalogoVista()
        {
            this.tCatalogoDetalleVistas = new HashSet<tCatalogoDetalleVista>();
        }
    
        public int idVista { get; set; }
        public string Numero { get; set; }
        public int idUsuario { get; set; }
        public Nullable<int> idClienteFisico { get; set; }
        public Nullable<int> idClienteMoral { get; set; }
        public Nullable<int> idDespacho { get; set; }
        public Nullable<int> idDespachoReferencia { get; set; }
        public int idSucursal { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal CantidadProductos { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Total { get; set; }
        public short Estatus { get; set; }
        public byte TipoCliente { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> ModificadoPor { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCatalogoDetalleVista> tCatalogoDetalleVistas { get; set; }
        public virtual tUsuario tUsuario { get; set; }
        public virtual tClientesFisico tClientesFisico { get; set; }
        public virtual tClientesMorale tClientesMorale { get; set; }
        public virtual tDespacho tDespacho { get; set; }
        public virtual tDespacho tDespacho1 { get; set; }
        public virtual tSucursale tSucursale { get; set; }
        public virtual tUsuario tUsuario1 { get; set; }
        public virtual tUsuario tUsuario2 { get; set; }
    }
}
