//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCatalogoDetalleDevolucion
    {
        public int idDetalleDevoluciones { get; set; }
        public int idDetalleVista { get; set; }
        public decimal Devolucion { get; set; }
        public System.DateTime Fecha { get; set; }
        public int idVerificador { get; set; }
        public string Comentarios { get; set; }
    
        public virtual tCatalogoDetalleVista tCatalogoDetalleVista { get; set; }
        public virtual tUsuario tUsuario { get; set; }
    }
}
