//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCatalogoSucursal
    {
        public int idCatalogoSucursal { get; set; }
        public int idCatalogo { get; set; }
        public int idSucursal { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> ModificadoPor { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
    
        public virtual tCatalogo tCatalogo { get; set; }
        public virtual tUsuario tUsuario { get; set; }
        public virtual tSucursale tSucursale { get; set; }
        public virtual tUsuario tUsuario1 { get; set; }
    }
}
