//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCatalogo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tCatalogo()
        {
            this.tCatalogoDetalleVistas = new HashSet<tCatalogoDetalleVista>();
            this.tCatalogoSucursals = new HashSet<tCatalogoSucursal>();
        }
    
        public int idCatalogo { get; set; }
        public string Modelo { get; set; }
        public string Volumen { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public Nullable<int> idSubcategoria { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> ModificadoPor { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Codigo { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public Nullable<int> idCatalogoMarca { get; set; }
    
        public virtual tCatalogoCategoria tCatalogoCategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCatalogoDetalleVista> tCatalogoDetalleVistas { get; set; }
        public virtual tCatalogoMarca tCatalogoMarca { get; set; }
        public virtual tCatalogoProveedor tCatalogoProveedor { get; set; }
        public virtual tUsuario tUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCatalogoSucursal> tCatalogoSucursals { get; set; }
        public virtual tCatalogoSubcategoria tCatalogoSubcategoria { get; set; }
        public virtual tUsuario tUsuario1 { get; set; }
    }
}
