//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tClientesTiendaVirtual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tClientesTiendaVirtual()
        {
            this.tCarritoes = new HashSet<tCarrito>();
            this.tFacturacionTiendaVirtuals = new HashSet<tFacturacionTiendaVirtual>();
            this.tRespaldoVentasEnLineas = new HashSet<tRespaldoVentasEnLinea>();
            this.tVentasEnLineas = new HashSet<tVentasEnLinea>();
        }
    
        public int idCliente { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Contrasena { get; set; }
        public string Calle { get; set; }
        public string NumInt { get; set; }
        public string NumExt { get; set; }
        public string Colonia { get; set; }
        public string CP { get; set; }
        public string TelefonoCelular { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public Nullable<short> Sexo { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> Notificar { get; set; }
        public Nullable<bool> TipoDireccion { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> idMunicipio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCarrito> tCarritoes { get; set; }
        public virtual tMunicipio tMunicipio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tFacturacionTiendaVirtual> tFacturacionTiendaVirtuals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRespaldoVentasEnLinea> tRespaldoVentasEnLineas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tVentasEnLinea> tVentasEnLineas { get; set; }
    }
}
