//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCotizacionDetalle
    {
        public int idCotizacionDetalle { get; set; }
        public int idCotizacion { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> idServicio { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<int> idCredito { get; set; }
        public Nullable<short> Tipo { get; set; }
        public string Comentarios { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public Nullable<int> idVista { get; set; }
        public Nullable<int> idPromocion { get; set; }
        public Nullable<decimal> CostoPromocion { get; set; }
        public Nullable<int> idTipoPromocion { get; set; }
        public Nullable<int> idProductoPadre { get; set; }
    
        public virtual tCotizacion tCotizacion { get; set; }
        public virtual tNotasCredito tNotasCredito { get; set; }
        public virtual tPromocione tPromocione { get; set; }
        public virtual tProducto tProducto { get; set; }
        public virtual tProducto tProducto1 { get; set; }
        public virtual tSucursale tSucursale { get; set; }
        public virtual tTipoPromocion tTipoPromocion { get; set; }
    }
}
