//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDescuento
    {
        public int idDescuento { get; set; }
        public Nullable<decimal> RangoInicial { get; set; }
        public Nullable<decimal> RangoFinal { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
        public Nullable<short> TipoCliente { get; set; }
    }
}
