//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDetallePromocion
    {
        public int idDetallePromocion { get; set; }
        public int idPromocion { get; set; }
        public int idProducto { get; set; }
        public decimal Cantidad { get; set; }
    
        public virtual tPromocione tPromocione { get; set; }
        public virtual tProducto tProducto { get; set; }
    }
}
