//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDetalleMesaRegalo
    {
        public int idDetalle { get; set; }
        public int idMesaRegalo { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> idServicio { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<short> Tipo { get; set; }
        public string Comentario { get; set; }
        public Nullable<short> Estatus { get; set; }
        public string Descripcion { get; set; }
    
        public virtual tMesaRegalo tMesaRegalo { get; set; }
        public virtual tProducto tProducto { get; set; }
        public virtual tServicio tServicio { get; set; }
    }
}
