//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDetalleCarrito
    {
        public int idDetalleCarrito { get; set; }
        public Nullable<int> idCarrito { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<int> idPromocion { get; set; }
    
        public virtual tCarrito tCarrito { get; set; }
        public virtual tProducto tProducto { get; set; }
        public virtual tPromocione tPromocione { get; set; }
    }
}
