//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDetalleCredito
    {
        public int idDetalleCredito { get; set; }
        public Nullable<int> idNotaCredito { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> idServicio { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<int> idSucursal { get; set; }
    
        public virtual tNotasCredito tNotasCredito { get; set; }
        public virtual tProducto tProducto { get; set; }
        public virtual tServicio tServicio { get; set; }
        public virtual tSucursale tSucursale { get; set; }
    }
}
