//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDetallePedido
    {
        public int idDetallePedido { get; set; }
        public int idPedido { get; set; }
        public Nullable<int> idServicio { get; set; }
        public Nullable<int> idCredito { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Descuento { get; set; }
    
        public virtual tNotasCredito tNotasCredito { get; set; }
        public virtual tPedido tPedido { get; set; }
    }
}
