//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDetalleReparacione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tDetalleReparacione()
        {
            this.tHistoricoReparaciones = new HashSet<tHistoricoReparacione>();
        }
    
        public int idDetalleReparacion { get; set; }
        public int idReparacion { get; set; }
        public int idProducto { get; set; }
        public int idSucursal { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Pendiente { get; set; }
        public string Comentarios { get; set; }
    
        public virtual tProducto tProducto { get; set; }
        public virtual tReparacione tReparacione { get; set; }
        public virtual tSucursale tSucursale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tHistoricoReparacione> tHistoricoReparaciones { get; set; }
    }
}
