//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDetalleVista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tDetalleVista()
        {
            this.tDetalleDevoluciones = new HashSet<tDetalleDevolucione>();
        }
    
        public int idDetalleVista { get; set; }
        public int idVista { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public Nullable<short> Estatus { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<decimal> Devolucion { get; set; }
        public Nullable<decimal> Venta { get; set; }
        public string Comentarios { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleDevolucione> tDetalleDevoluciones { get; set; }
        public virtual tProducto tProducto { get; set; }
        public virtual tSucursale tSucursale { get; set; }
        public virtual tUsuario tUsuario { get; set; }
        public virtual tVista tVista { get; set; }
    }
}
