//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDetalleVentaMesaRegalo
    {
        public int idDetalleVenta { get; set; }
        public int idVenta { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> idServicio { get; set; }
        public Nullable<int> idCredito { get; set; }
        public string NotaCredito { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<short> Tipo { get; set; }
        public string Comentarios { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
    
        public virtual tNotasCredito tNotasCredito { get; set; }
        public virtual tProducto tProducto { get; set; }
        public virtual tVentaMesaRegalo tVentaMesaRegalo { get; set; }
    }
}
