//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDetalleVentaEnLinea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tDetalleVentaEnLinea()
        {
            this.tDistribucionVentaEnLineas = new HashSet<tDistribucionVentaEnLinea>();
        }
    
        public int idDetalleVenta { get; set; }
        public int idVenta { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<int> idPromocion { get; set; }
        public Nullable<int> idServicio { get; set; }
        public Nullable<bool> Tipo { get; set; }
    
        public virtual tProducto tProducto { get; set; }
        public virtual tPromocione tPromocione { get; set; }
        public virtual tServicio tServicio { get; set; }
        public virtual tVentasEnLinea tVentasEnLinea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDistribucionVentaEnLinea> tDistribucionVentaEnLineas { get; set; }
    }
}
