//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDetalleDevolucione
    {
        public int idDetalleDevoluciones { get; set; }
        public Nullable<int> idDetalleVista { get; set; }
        public Nullable<decimal> Devolucion { get; set; }
        public Nullable<decimal> Venta { get; set; }
        public string Remision { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> idVerificador { get; set; }
    
        public virtual tDetalleVista tDetalleVista { get; set; }
        public virtual tUsuario tUsuario { get; set; }
    }
}
