//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEmpresa
    {
        public int idEmpresa { get; set; }
        public string Nombre { get; set; }
        public string RazonSocial { get; set; }
        public string NombreComercial { get; set; }
        public string DomicilioFiscal { get; set; }
        public string DomicilioEntraga { get; set; }
        public int idNacionalidad { get; set; }
        public string RFC { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Correo { get; set; }
        public string SitioWeb { get; set; }
        public string SitioWebCatalogo { get; set; }
        public string Usuario { get; set; }
        public string Contrasena { get; set; }
    
        public virtual tNacionalidad tNacionalidad { get; set; }
    }
}
