//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEntrada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tEntrada()
        {
            this.tFormaPagoes = new HashSet<tFormaPago>();
            this.tHistorialCreditoes = new HashSet<tHistorialCredito>();
            this.tSalidas = new HashSet<tSalida>();
        }
    
        public int idEntrada { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> EntregadaPor { get; set; }
        public string EntregadaOtro { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> ModificadoPor { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> idVenta { get; set; }
        public Nullable<int> idReporteCaja { get; set; }
    
        public virtual tUsuario tUsuario { get; set; }
        public virtual tUsuario tUsuario1 { get; set; }
        public virtual tReporteCaja tReporteCaja { get; set; }
        public virtual tVenta tVenta { get; set; }
        public virtual tUsuario tUsuario2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tFormaPago> tFormaPagoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tHistorialCredito> tHistorialCreditoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSalida> tSalidas { get; set; }
    }
}
