//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEvento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tEvento()
        {
            this.tUsuarioEventoes = new HashSet<tUsuarioEvento>();
            this.tPreCotizacionDetalles = new HashSet<tPreCotizacionDetalle>();
            this.tPreCotizacions = new HashSet<tPreCotizacion>();
        }
    
        public int idEvento { get; set; }
        public string Nombre { get; set; }
        public System.DateTime Fecha { get; set; }
        public string HoraInicio { get; set; }
        public string Lugar { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<bool> Cancelado { get; set; }
        public string HoraFin { get; set; }
        public Nullable<bool> TodoDia { get; set; }
        public string Color { get; set; }
        public string Fondo { get; set; }
        public string Fuente { get; set; }
        public Nullable<System.DateTime> FechaRecordatorio { get; set; }
        public string HoraRecordatorio { get; set; }
        public Nullable<byte> Tipo { get; set; }
    
        public virtual tUsuario tUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tUsuarioEvento> tUsuarioEventoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPreCotizacionDetalle> tPreCotizacionDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPreCotizacion> tPreCotizacions { get; set; }
    }
}
