//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFormaPagoCredito
    {
        public int idFormaPagoCredito { get; set; }
        public int idHistorialCredito { get; set; }
        public Nullable<int> FormaPago { get; set; }
        public Nullable<int> TipoTarjeta { get; set; }
        public string Banco { get; set; }
        public string Titular { get; set; }
        public string NumCheque { get; set; }
        public Nullable<int> idNotaCredito { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> ModificadoPor { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
        public Nullable<int> idPagoMeses { get; set; }
        public Nullable<int> idCuentaBancos { get; set; }
        public Nullable<int> idTipoTerminales { get; set; }
    
        public virtual tCatalogoCuentaBanco tCatalogoCuentaBanco { get; set; }
        public virtual tCatalogoTipoTerminale tCatalogoTipoTerminale { get; set; }
        public virtual tUsuario tUsuario { get; set; }
        public virtual tHistorialCredito tHistorialCredito { get; set; }
        public virtual tNotasCredito tNotasCredito { get; set; }
        public virtual tPagoMes tPagoMes { get; set; }
        public virtual tUsuario tUsuario1 { get; set; }
    }
}
