//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFormaPago
    {
        public int idFormaPago { get; set; }
        public Nullable<int> idVenta { get; set; }
        public Nullable<int> FormaPago { get; set; }
        public Nullable<int> TipoTarjeta { get; set; }
        public string Banco { get; set; }
        public string Titular { get; set; }
        public string NumCheque { get; set; }
        public string NumIFE { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<System.DateTime> FechaLimitePago { get; set; }
        public Nullable<short> Estatus { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<bool> IVA { get; set; }
        public Nullable<decimal> CantidadIVA { get; set; }
        public Nullable<int> idCuenta { get; set; }
        public string Voucher { get; set; }
        public Nullable<int> idNotaCredito { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<bool> Entrada { get; set; }
        public Nullable<int> idEntrada { get; set; }
        public Nullable<int> idPagoMeses { get; set; }
        public Nullable<int> idTipoTerminales { get; set; }
        public Nullable<int> idCuentaBancos { get; set; }
    
        public virtual tCatalogoCuentaBanco tCatalogoCuentaBanco { get; set; }
        public virtual tCatalogoTipoTerminale tCatalogoTipoTerminale { get; set; }
        public virtual tCuenta tCuenta { get; set; }
        public virtual tEntrada tEntrada { get; set; }
        public virtual tNotasCredito tNotasCredito { get; set; }
        public virtual tPagoMes tPagoMes { get; set; }
        public virtual tVenta tVenta { get; set; }
    }
}
