//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tHistorialCredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tHistorialCredito()
        {
            this.tFormaPagoCreditoes = new HashSet<tFormaPagoCredito>();
        }
    
        public int idHistorialCredito { get; set; }
        public Nullable<int> idVenta { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string Comentario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<short> Estatus { get; set; }
        public Nullable<decimal> Restante { get; set; }
        public Nullable<decimal> CantidadIVA { get; set; }
        public Nullable<bool> IVA { get; set; }
        public Nullable<int> idCuenta { get; set; }
        public string Voucher { get; set; }
        public Nullable<bool> Entrada { get; set; }
        public Nullable<int> idEntrada { get; set; }
    
        public virtual tCuenta tCuenta { get; set; }
        public virtual tEntrada tEntrada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tFormaPagoCredito> tFormaPagoCreditoes { get; set; }
        public virtual tVenta tVenta { get; set; }
    }
}
