//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tHistEstatusServicio
    {
        public int idHistEstatusServicio { get; set; }
        public Nullable<int> idPreCotizacion { get; set; }
        public Nullable<int> idPrecotizacionDetalle { get; set; }
        public Nullable<int> idEstatusServicio { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
    
        public virtual tEstatusServicio tEstatusServicio { get; set; }
        public virtual tPreCotizacionDetalle tPreCotizacionDetalle { get; set; }
        public virtual tPreCotizacion tPreCotizacion { get; set; }
    }
}
