//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tHistoricoRecepcion
    {
        public int idHistoricoRecepcion { get; set; }
        public int idDetalleRecepcion { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
    
        public virtual tDetalleRecepcion tDetalleRecepcion { get; set; }
    }
}
