//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tInventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tInventario()
        {
            this.tBitacoraProductosInventarios = new HashSet<tBitacoraProductosInventario>();
            this.tProductosInventarios = new HashSet<tProductosInventario>();
        }
    
        public int idInventario { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<short> Estatus { get; set; }
        public Nullable<int> DiferenciasNegativas { get; set; }
        public Nullable<int> DiferenciasPositivas { get; set; }
        public Nullable<int> ArticulosInventarioAnterior { get; set; }
        public Nullable<int> ArticulosInventarioActual { get; set; }
        public Nullable<decimal> CostoInventarioAnterior { get; set; }
        public Nullable<decimal> CostoInventarioActual { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBitacoraProductosInventario> tBitacoraProductosInventarios { get; set; }
        public virtual tSucursale tSucursale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tProductosInventario> tProductosInventarios { get; set; }
    }
}
