//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNotasCredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tNotasCredito()
        {
            this.tBorradorDetalleVentas = new HashSet<tBorradorDetalleVenta>();
            this.tCotizacionDetalles = new HashSet<tCotizacionDetalle>();
            this.tDetalleCreditoes = new HashSet<tDetalleCredito>();
            this.tDetallePedidoes = new HashSet<tDetallePedido>();
            this.tDetalleVentas = new HashSet<tDetalleVenta>();
            this.tDetalleVentaMesaRegalos = new HashSet<tDetalleVentaMesaRegalo>();
            this.tFormaPagoes = new HashSet<tFormaPago>();
            this.tFormaPagoCreditoes = new HashSet<tFormaPagoCredito>();
            this.tMesaRegalos = new HashSet<tMesaRegalo>();
        }
    
        public int idNotaCredito { get; set; }
        public string Remision { get; set; }
        public Nullable<int> idVenta { get; set; }
        public Nullable<int> idVendedor { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaVigencia { get; set; }
        public Nullable<short> Estatus { get; set; }
        public Nullable<int> idCustomerP { get; set; }
        public Nullable<int> idCustomerM { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> idDespacho { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> ModificadoPor { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
        public Nullable<int> idTipoNotaCredito { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBorradorDetalleVenta> tBorradorDetalleVentas { get; set; }
        public virtual tClientesFisico tClientesFisico { get; set; }
        public virtual tClientesMorale tClientesMorale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCotizacionDetalle> tCotizacionDetalles { get; set; }
        public virtual tDespacho tDespacho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleCredito> tDetalleCreditoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetallePedido> tDetallePedidoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleVenta> tDetalleVentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleVentaMesaRegalo> tDetalleVentaMesaRegalos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tFormaPago> tFormaPagoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tFormaPagoCredito> tFormaPagoCreditoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMesaRegalo> tMesaRegalos { get; set; }
        public virtual tUsuario tUsuario { get; set; }
        public virtual tTipoNotaCredito tTipoNotaCredito { get; set; }
        public virtual tVenta tVenta { get; set; }
        public virtual tUsuario tUsuario1 { get; set; }
        public virtual tUsuario tUsuario2 { get; set; }
    }
}
