//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tOrden()
        {
            this.tCantidadProductosOrdens = new HashSet<tCantidadProductosOrden>();
            this.tOrdenProductoes = new HashSet<tOrdenProducto>();
        }
    
        public int idOrden { get; set; }
        public string Orden { get; set; }
        public int idEmpresa { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public System.DateTime FechaCaptura { get; set; }
        public string Factura { get; set; }
        public Nullable<short> Estatus { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public Nullable<decimal> CostoDolar { get; set; }
        public Nullable<int> TipoMoneda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCantidadProductosOrden> tCantidadProductosOrdens { get; set; }
        public virtual tProveedore tProveedore { get; set; }
        public virtual tTipoMoneda tTipoMoneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrdenProducto> tOrdenProductoes { get; set; }
    }
}
