//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPreCotProveedoresTela
    {
        public int idPreCotProveedoresTelas { get; set; }
        public Nullable<int> idPreCotDetalleProveedores { get; set; }
        public Nullable<int> idServicio { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public Nullable<int> idTextiles { get; set; }
        public Nullable<decimal> ValorMts { get; set; }
    
        public virtual tPreCotDetalleProveedore tPreCotDetalleProveedore { get; set; }
        public virtual tTextile tTextile { get; set; }
    }
}
