//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPreCotDetalleTipoTela
    {
        public int idPreCotDetalleTipoTela { get; set; }
        public Nullable<int> idPreCotizacionDetalle { get; set; }
        public Nullable<int> idServicio { get; set; }
        public Nullable<int> idTextiles { get; set; }
        public Nullable<decimal> CostoPorMts { get; set; }
        public Nullable<decimal> ValorMts { get; set; }
        public Nullable<decimal> CostoTotal { get; set; }
    
        public virtual tServicio tServicio { get; set; }
        public virtual tTextile tTextile { get; set; }
        public virtual tPreCotizacionDetalle tPreCotizacionDetalle { get; set; }
        public virtual tPreCotizacionDetalle tPreCotizacionDetalle1 { get; set; }
    }
}
