//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPreCotDetalleProveedore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tPreCotDetalleProveedore()
        {
            this.tPreCotProveedoresTelas = new HashSet<tPreCotProveedoresTela>();
        }
    
        public int idPreCotDetalleProveedores { get; set; }
        public Nullable<int> idPreCotizacionDetalle { get; set; }
        public Nullable<int> idServicio { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public Nullable<decimal> CostoFabricacion { get; set; }
        public Nullable<int> DiasFabricacion { get; set; }
        public string ComentariosProveedor { get; set; }
        public string ComentariosComprador { get; set; }
        public Nullable<int> Asignado { get; set; }
        public Nullable<int> Enviado { get; set; }
    
        public virtual tProveedore tProveedore { get; set; }
        public virtual tServicio tServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPreCotProveedoresTela> tPreCotProveedoresTelas { get; set; }
        public virtual tPreCotizacionDetalle tPreCotizacionDetalle { get; set; }
    }
}
