//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPreCotizacionDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tPreCotizacionDetalle()
        {
            this.tHistEstatusServicios = new HashSet<tHistEstatusServicio>();
            this.tPreCotDetalleMedidas = new HashSet<tPreCotDetalleMedida>();
            this.tPreCotDetalleProveedores = new HashSet<tPreCotDetalleProveedore>();
            this.tPreCotDetalleTipoTelas = new HashSet<tPreCotDetalleTipoTela>();
            this.tPreCotDetalleTipoTelas1 = new HashSet<tPreCotDetalleTipoTela>();
        }
    
        public int idPreCotizacionDetalle { get; set; }
        public int idPreCotizacion { get; set; }
        public Nullable<int> idServicio { get; set; }
        public string Descripcion { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Imagen { get; set; }
        public string PDF { get; set; }
        public Nullable<int> idEstatusServicio { get; set; }
        public Nullable<int> idEvento { get; set; }
    
        public virtual tEstatusServicio tEstatusServicio { get; set; }
        public virtual tEvento tEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tHistEstatusServicio> tHistEstatusServicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPreCotDetalleMedida> tPreCotDetalleMedidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPreCotDetalleProveedore> tPreCotDetalleProveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPreCotDetalleTipoTela> tPreCotDetalleTipoTelas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPreCotDetalleTipoTela> tPreCotDetalleTipoTelas1 { get; set; }
        public virtual tServicio tServicio { get; set; }
        public virtual tPreCotizacion tPreCotizacion { get; set; }
        public virtual tPreCotizacion tPreCotizacion1 { get; set; }
    }
}
