//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPromocione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tPromocione()
        {
            this.tBorradorDetalleVentas = new HashSet<tBorradorDetalleVenta>();
            this.tCotizacionDetalles = new HashSet<tCotizacionDetalle>();
            this.tDetalleCarritoes = new HashSet<tDetalleCarrito>();
            this.tDetallePromocions = new HashSet<tDetallePromocion>();
            this.tDetalleVentas = new HashSet<tDetalleVenta>();
            this.tDetalleVentaEnLineas = new HashSet<tDetalleVentaEnLinea>();
            this.tRespaldoDetalleVentaEnLineas = new HashSet<tRespaldoDetalleVentaEnLinea>();
        }
    
        public int idPromocion { get; set; }
        public int idTipoPromocion { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> ModificadoPor { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBorradorDetalleVenta> tBorradorDetalleVentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCotizacionDetalle> tCotizacionDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleCarrito> tDetalleCarritoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetallePromocion> tDetallePromocions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleVenta> tDetalleVentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleVentaEnLinea> tDetalleVentaEnLineas { get; set; }
        public virtual tUsuario tUsuario { get; set; }
        public virtual tTipoPromocion tTipoPromocion { get; set; }
        public virtual tUsuario tUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRespaldoDetalleVentaEnLinea> tRespaldoDetalleVentaEnLineas { get; set; }
    }
}
