//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProductosInventario
    {
        public int idProductosInventario { get; set; }
        public Nullable<int> idInventario { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> CantidadAnterior { get; set; }
        public Nullable<int> CantidadActual { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<bool> Inventariado { get; set; }
    
        public virtual tInventario tInventario { get; set; }
        public virtual tProducto tProducto { get; set; }
    }
}
