//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tProducto()
        {
            this.tBitacoraProductos = new HashSet<tBitacoraProducto>();
            this.tBitacoraProductosInventarios = new HashSet<tBitacoraProductosInventario>();
            this.tBorradorDetalleVentas = new HashSet<tBorradorDetalleVenta>();
            this.tBorradorDetalleVentas1 = new HashSet<tBorradorDetalleVenta>();
            this.tBorradorDetalleVistas = new HashSet<tBorradorDetalleVista>();
            this.tCantidadProductosOrdens = new HashSet<tCantidadProductosOrden>();
            this.tCotizacionDetalles = new HashSet<tCotizacionDetalle>();
            this.tCotizacionDetalles1 = new HashSet<tCotizacionDetalle>();
            this.tDetalleCarritoes = new HashSet<tDetalleCarrito>();
            this.tDetalleCreditoes = new HashSet<tDetalleCredito>();
            this.tDetalleMesaRegalos = new HashSet<tDetalleMesaRegalo>();
            this.tDetallePromocions = new HashSet<tDetallePromocion>();
            this.tDetalleRecepcions = new HashSet<tDetalleRecepcion>();
            this.tDetalleReparaciones = new HashSet<tDetalleReparacione>();
            this.tDetalleTransferencias = new HashSet<tDetalleTransferencia>();
            this.tDetalleVentas = new HashSet<tDetalleVenta>();
            this.tDetalleVentas1 = new HashSet<tDetalleVenta>();
            this.tDetalleVentaEnLineas = new HashSet<tDetalleVentaEnLinea>();
            this.tDetalleVentaMesaRegalos = new HashSet<tDetalleVentaMesaRegalo>();
            this.tDetalleVistas = new HashSet<tDetalleVista>();
            this.tDistribucionVentaEnLineas = new HashSet<tDistribucionVentaEnLinea>();
            this.tOrdenProductoes = new HashSet<tOrdenProducto>();
            this.tProductosInventarios = new HashSet<tProductosInventario>();
            this.tProductosSucursals = new HashSet<tProductosSucursal>();
            this.tRespaldoDetalleVentaEnLineas = new HashSet<tRespaldoDetalleVentaEnLinea>();
            this.tRespaldoProductosSucursals = new HashSet<tRespaldoProductosSucursal>();
        }
    
        public int idProducto { get; set; }
        public string Nombre { get; set; }
        public string NombreComercial { get; set; }
        public string Descripcion { get; set; }
        public decimal PrecioVenta { get; set; }
        public int idProveedor { get; set; }
        public int idCategoria { get; set; }
        public Nullable<int> idSubcategoria { get; set; }
        public string Color { get; set; }
        public Nullable<int> idMaterial { get; set; }
        public string Medida { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public string Codigo { get; set; }
        public Nullable<short> Estatus { get; set; }
        public string Extension { get; set; }
        public string urlImagen { get; set; }
        public Nullable<short> TipoImagen { get; set; }
        public string NombreImagen { get; set; }
        public Nullable<decimal> PrecioCompra { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> ModificadoPor { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBitacoraProducto> tBitacoraProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBitacoraProductosInventario> tBitacoraProductosInventarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBorradorDetalleVenta> tBorradorDetalleVentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBorradorDetalleVenta> tBorradorDetalleVentas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBorradorDetalleVista> tBorradorDetalleVistas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCantidadProductosOrden> tCantidadProductosOrdens { get; set; }
        public virtual tCategoria tCategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCotizacionDetalle> tCotizacionDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCotizacionDetalle> tCotizacionDetalles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleCarrito> tDetalleCarritoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleCredito> tDetalleCreditoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleMesaRegalo> tDetalleMesaRegalos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetallePromocion> tDetallePromocions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleRecepcion> tDetalleRecepcions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleReparacione> tDetalleReparaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleTransferencia> tDetalleTransferencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleVenta> tDetalleVentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleVenta> tDetalleVentas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleVentaEnLinea> tDetalleVentaEnLineas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleVentaMesaRegalo> tDetalleVentaMesaRegalos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleVista> tDetalleVistas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDistribucionVentaEnLinea> tDistribucionVentaEnLineas { get; set; }
        public virtual tMateriale tMateriale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrdenProducto> tOrdenProductoes { get; set; }
        public virtual tUsuario tUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tProductosInventario> tProductosInventarios { get; set; }
        public virtual tProveedore tProveedore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tProductosSucursal> tProductosSucursals { get; set; }
        public virtual tSubcategoria tSubcategoria { get; set; }
        public virtual tUsuario tUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRespaldoDetalleVentaEnLinea> tRespaldoDetalleVentaEnLineas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRespaldoProductosSucursal> tRespaldoProductosSucursals { get; set; }
    }
}
