//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tProveedores()
        {
            this.tOrden = new HashSet<tOrden>();
            this.tProductos = new HashSet<tProducto>();
        }
    
        public int idProveedor { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> Credito { get; set; }
        public Nullable<int> DiasCredito { get; set; }
        public Nullable<int> idCuentaBancariaMXN { get; set; }
        public Nullable<int> idCuentaBancariaINT { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<decimal> Flete { get; set; }
        public Nullable<decimal> Importacion { get; set; }
        public string NombreEmpresa { get; set; }
        public string RazonSocial { get; set; }
        public string NombreComercial { get; set; }
        public string DomicilioFiscal { get; set; }
        public string DomicilioEntrega { get; set; }
        public string Nacionalidad { get; set; }
        public string RFC { get; set; }
        public string SitioWeb { get; set; }
        public string SitioWebCatalogo { get; set; }
        public string Usuario { get; set; }
        public string Contrasena { get; set; }
        public Nullable<short> Estatus { get; set; }
    
        public virtual tCuentaBancariaINT tCuentaBancariaINT { get; set; }
        public virtual tCuentaBancariaMXN tCuentaBancariaMXN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrden> tOrden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tProducto> tProductos { get; set; }
    }
}
