//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRecepcione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tRecepcione()
        {
            this.tDetalleRecepcions = new HashSet<tDetalleRecepcion>();
        }
    
        public int idRecepcion { get; set; }
        public string Numero { get; set; }
        public Nullable<int> idTransferencia { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> CantidadProductos { get; set; }
        public Nullable<decimal> CostoTotal { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> ModificadoPor { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleRecepcion> tDetalleRecepcions { get; set; }
        public virtual tUsuario tUsuario { get; set; }
        public virtual tSucursale tSucursale { get; set; }
        public virtual tTransferencia tTransferencia { get; set; }
        public virtual tUsuario tUsuario1 { get; set; }
        public virtual tUsuario tUsuario2 { get; set; }
    }
}
