//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tReporteDiarioInventario
    {
        public int ReporteDiarioInventario { get; set; }
        public Nullable<decimal> CantidadProductos { get; set; }
        public string CostoInventario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
