//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tReporteComisionesEspeciale
    {
        public int idVentasComisiones { get; set; }
        public int idVendedor { get; set; }
        public Nullable<int> FormaPago { get; set; }
        public string NumCheque { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<short> Concepto { get; set; }
        public string Detalle { get; set; }
        public Nullable<decimal> TotalNetoVendido { get; set; }
        public Nullable<decimal> PorcentajeComision { get; set; }
    
        public virtual tUsuario tUsuario { get; set; }
    }
}
