//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRespaldoVentasEnLinea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tRespaldoVentasEnLinea()
        {
            this.tRespaldoDetalleVentaEnLineas = new HashSet<tRespaldoDetalleVentaEnLinea>();
        }
    
        public int idRespaldoVenta { get; set; }
        public int idCarrito { get; set; }
        public int idCliente { get; set; }
        public int idTipoEntrega { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> CantidadProductos { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<int> Descuento { get; set; }
        public Nullable<decimal> GastosEnvio { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string idClienteOpenPay { get; set; }
        public string idOrdenOpenPay { get; set; }
    
        public virtual tCarrito tCarrito { get; set; }
        public virtual tCarrito tCarrito1 { get; set; }
        public virtual tClientesTiendaVirtual tClientesTiendaVirtual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRespaldoDetalleVentaEnLinea> tRespaldoDetalleVentaEnLineas { get; set; }
    }
}
