//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRespaldoDetalleVentaEnLinea
    {
        public int idRespaldoDetalleVenta { get; set; }
        public int idRespaldoVenta { get; set; }
        public Nullable<int> idProducto { get; set; }
        public decimal Precio { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Descuento { get; set; }
        public Nullable<int> idPromocion { get; set; }
        public Nullable<int> idServicio { get; set; }
        public Nullable<bool> Tipo { get; set; }
    
        public virtual tProducto tProducto { get; set; }
        public virtual tPromocione tPromocione { get; set; }
        public virtual tRespaldoVentasEnLinea tRespaldoVentasEnLinea { get; set; }
        public virtual tServicio tServicio { get; set; }
    }
}
