//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSalida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tSalida()
        {
            this.tSalida1 = new HashSet<tSalida>();
        }
    
        public int idSalida { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> RecibidaPor { get; set; }
        public string RecibidaOtro { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> ModificadoPor { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> idVenta { get; set; }
        public Nullable<int> idReporteCaja { get; set; }
        public Nullable<int> idEntrada { get; set; }
        public Nullable<int> fkSalida { get; set; }
    
        public virtual tEntrada tEntrada { get; set; }
        public virtual tReporteCaja tReporteCaja { get; set; }
        public virtual tUsuario tUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSalida> tSalida1 { get; set; }
        public virtual tSalida tSalida2 { get; set; }
        public virtual tVenta tVenta { get; set; }
        public virtual tUsuario tUsuario1 { get; set; }
        public virtual tUsuario tUsuario2 { get; set; }
    }
}
