//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tServicioMedidasEstandar
    {
        public int idServicioMedidasEstandar { get; set; }
        public Nullable<int> idServicio { get; set; }
        public Nullable<int> idTipoMedida { get; set; }
        public Nullable<decimal> Valor { get; set; }
    
        public virtual tServicio tServicio { get; set; }
        public virtual tTipoMedida tTipoMedida { get; set; }
    }
}
