//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTextile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tTextile()
        {
            this.tPreCotDetalleTipoTelas = new HashSet<tPreCotDetalleTipoTela>();
            this.tPreCotProveedoresTelas = new HashSet<tPreCotProveedoresTela>();
        }
    
        public int idTextiles { get; set; }
        public string Marca { get; set; }
        public string NombreTela { get; set; }
        public string Coleccion { get; set; }
        public Nullable<decimal> AnchoTela { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string Moneda { get; set; }
        public Nullable<int> Habilitado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPreCotDetalleTipoTela> tPreCotDetalleTipoTelas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPreCotProveedoresTela> tPreCotProveedoresTelas { get; set; }
    }
}
