//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTicket
    {
        public int idTicket { get; set; }
        public string Codigo { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public int idEstatusTicket { get; set; }
        public int CreadoPor { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> ModificadoPor { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> idTipoTicket { get; set; }
        public Nullable<int> idPrioridadTicket { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> Cerrado { get; set; }
        public Nullable<int> idUsuarioAsignado { get; set; }
        public Nullable<decimal> Estimado { get; set; }
        public Nullable<decimal> Completado { get; set; }
        public Nullable<bool> Autorizado { get; set; }
        public Nullable<int> AutorizadoPor { get; set; }
        public Nullable<System.DateTime> FechaAutorizado { get; set; }
    
        public virtual tEstatusTicket tEstatusTicket { get; set; }
        public virtual tPrioridadTicket tPrioridadTicket { get; set; }
        public virtual tUsuario tUsuario { get; set; }
        public virtual tUsuario tUsuario1 { get; set; }
        public virtual tTipoTicket tTipoTicket { get; set; }
        public virtual tUsuario tUsuario2 { get; set; }
        public virtual tUsuario tUsuario3 { get; set; }
    }
}
