//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUsuarioEvento
    {
        public int idUsuarioEvento { get; set; }
        public int idEvento { get; set; }
        public int idUsuario { get; set; }
    
        public virtual tEvento tEvento { get; set; }
        public virtual tUsuario tUsuario { get; set; }
    }
}
