//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tUsuario()
        {
            this.tActividadVendedores = new HashSet<tActividadVendedore>();
            this.tBanners = new HashSet<tBanner>();
            this.tBanners1 = new HashSet<tBanner>();
            this.tBitacoraProductos = new HashSet<tBitacoraProducto>();
            this.tBorradorVentas = new HashSet<tBorradorVenta>();
            this.tBorradorVentas1 = new HashSet<tBorradorVenta>();
            this.tBorradorVistas = new HashSet<tBorradorVista>();
            this.tBorradorVistas1 = new HashSet<tBorradorVista>();
            this.tCatalogoCategorias = new HashSet<tCatalogoCategoria>();
            this.tCatalogoCategorias1 = new HashSet<tCatalogoCategoria>();
            this.tCatalogoDetalleDevolucions = new HashSet<tCatalogoDetalleDevolucion>();
            this.tCatalogoMarcas = new HashSet<tCatalogoMarca>();
            this.tCatalogoMarcas1 = new HashSet<tCatalogoMarca>();
            this.tCatalogos = new HashSet<tCatalogo>();
            this.tCatalogos1 = new HashSet<tCatalogo>();
            this.tCatalogoSubcategorias = new HashSet<tCatalogoSubcategoria>();
            this.tCatalogoSubcategorias1 = new HashSet<tCatalogoSubcategoria>();
            this.tCatalogoSucursals = new HashSet<tCatalogoSucursal>();
            this.tCatalogoSucursals1 = new HashSet<tCatalogoSucursal>();
            this.tCatalogoVistas = new HashSet<tCatalogoVista>();
            this.tCatalogoVistas1 = new HashSet<tCatalogoVista>();
            this.tCatalogoVistas2 = new HashSet<tCatalogoVista>();
            this.tClientesFisicos = new HashSet<tClientesFisico>();
            this.tClientesMorales = new HashSet<tClientesMorale>();
            this.tComisiones = new HashSet<tComisione>();
            this.tCotizacions = new HashSet<tCotizacion>();
            this.tCotizacions1 = new HashSet<tCotizacion>();
            this.tDespachoes = new HashSet<tDespacho>();
            this.tDetalleDevoluciones = new HashSet<tDetalleDevolucione>();
            this.tDetalleRecepcions = new HashSet<tDetalleRecepcion>();
            this.tDetalleRecepcions1 = new HashSet<tDetalleRecepcion>();
            this.tDetalleTransferencias = new HashSet<tDetalleTransferencia>();
            this.tDetalleTransferencias1 = new HashSet<tDetalleTransferencia>();
            this.tDetalleVistas = new HashSet<tDetalleVista>();
            this.tEntradas = new HashSet<tEntrada>();
            this.tEntradas1 = new HashSet<tEntrada>();
            this.tEntradas2 = new HashSet<tEntrada>();
            this.tErrores = new HashSet<tErrore>();
            this.tEventos = new HashSet<tEvento>();
            this.tFormaPagoCreditoes = new HashSet<tFormaPagoCredito>();
            this.tFormaPagoCreditoes1 = new HashSet<tFormaPagoCredito>();
            this.tHistoricoComisiones = new HashSet<tHistoricoComisione>();
            this.tHistoricoReparaciones = new HashSet<tHistoricoReparacione>();
            this.tMesaRegalos = new HashSet<tMesaRegalo>();
            this.tMesaRegalos1 = new HashSet<tMesaRegalo>();
            this.tNotasCreditoes = new HashSet<tNotasCredito>();
            this.tNotasCreditoes1 = new HashSet<tNotasCredito>();
            this.tNotasCreditoes2 = new HashSet<tNotasCredito>();
            this.tOrigenClientes = new HashSet<tOrigenCliente>();
            this.tOrigenClientes1 = new HashSet<tOrigenCliente>();
            this.tPagoMeses = new HashSet<tPagoMes>();
            this.tPagoMeses1 = new HashSet<tPagoMes>();
            this.tPedidos = new HashSet<tPedido>();
            this.tPedidos1 = new HashSet<tPedido>();
            this.tProductos = new HashSet<tProducto>();
            this.tProductos1 = new HashSet<tProducto>();
            this.tPromociones = new HashSet<tPromocione>();
            this.tPromociones1 = new HashSet<tPromocione>();
            this.tRecepciones = new HashSet<tRecepcione>();
            this.tRecepciones1 = new HashSet<tRecepcione>();
            this.tRecepciones2 = new HashSet<tRecepcione>();
            this.tReparaciones = new HashSet<tReparacione>();
            this.tReparaciones1 = new HashSet<tReparacione>();
            this.tReparaciones2 = new HashSet<tReparacione>();
            this.tReporteComisionesEspeciales = new HashSet<tReporteComisionesEspeciale>();
            this.tReporteVentasComisiones = new HashSet<tReporteVentasComisione>();
            this.tRespaldoProductosSucursals = new HashSet<tRespaldoProductosSucursal>();
            this.tSalidas = new HashSet<tSalida>();
            this.tSalidas1 = new HashSet<tSalida>();
            this.tSalidas2 = new HashSet<tSalida>();
            this.tTickets = new HashSet<tTicket>();
            this.tTickets1 = new HashSet<tTicket>();
            this.tTickets2 = new HashSet<tTicket>();
            this.tTickets3 = new HashSet<tTicket>();
            this.tTransferencias = new HashSet<tTransferencia>();
            this.tTransferencias1 = new HashSet<tTransferencia>();
            this.tTransferencias2 = new HashSet<tTransferencia>();
            this.tUsuarioEventoes = new HashSet<tUsuarioEvento>();
            this.tVentaMesaRegalos = new HashSet<tVentaMesaRegalo>();
            this.tVentaMesaRegalos1 = new HashSet<tVentaMesaRegalo>();
            this.tVentas = new HashSet<tVenta>();
            this.tVentas1 = new HashSet<tVenta>();
            this.tVentasEnLineas = new HashSet<tVentasEnLinea>();
            this.tVistas = new HashSet<tVista>();
            this.tVistas1 = new HashSet<tVista>();
            this.tVistas2 = new HashSet<tVista>();
            this.tSucursales = new HashSet<tSucursale>();
            this.tPreCotizacions = new HashSet<tPreCotizacion>();
            this.tPreCotizacions1 = new HashSet<tPreCotizacion>();
        }
    
        public int idUsuario { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Calle { get; set; }
        public string NumExt { get; set; }
        public string NumInt { get; set; }
        public string Colonia { get; set; }
        public Nullable<int> idMunicipio { get; set; }
        public Nullable<int> CP { get; set; }
        public string TelefonoCelular { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public string Correo { get; set; }
        public Nullable<int> idNivelAcademico { get; set; }
        public int idPerfil { get; set; }
        public string Contrasena { get; set; }
        public Nullable<short> Estatus { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public string Titulo { get; set; }
        public Nullable<short> Ventas { get; set; }
        public Nullable<int> Intentos { get; set; }
        public Nullable<short> Restringido { get; set; }
        public Nullable<bool> Facturar { get; set; }
        public Nullable<bool> AtencionTicket { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tActividadVendedore> tActividadVendedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBanner> tBanners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBanner> tBanners1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBitacoraProducto> tBitacoraProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBorradorVenta> tBorradorVentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBorradorVenta> tBorradorVentas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBorradorVista> tBorradorVistas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBorradorVista> tBorradorVistas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCatalogoCategoria> tCatalogoCategorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCatalogoCategoria> tCatalogoCategorias1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCatalogoDetalleDevolucion> tCatalogoDetalleDevolucions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCatalogoMarca> tCatalogoMarcas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCatalogoMarca> tCatalogoMarcas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCatalogo> tCatalogos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCatalogo> tCatalogos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCatalogoSubcategoria> tCatalogoSubcategorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCatalogoSubcategoria> tCatalogoSubcategorias1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCatalogoSucursal> tCatalogoSucursals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCatalogoSucursal> tCatalogoSucursals1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCatalogoVista> tCatalogoVistas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCatalogoVista> tCatalogoVistas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCatalogoVista> tCatalogoVistas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tClientesFisico> tClientesFisicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tClientesMorale> tClientesMorales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tComisione> tComisiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCotizacion> tCotizacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCotizacion> tCotizacions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDespacho> tDespachoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleDevolucione> tDetalleDevoluciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleRecepcion> tDetalleRecepcions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleRecepcion> tDetalleRecepcions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleTransferencia> tDetalleTransferencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleTransferencia> tDetalleTransferencias1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleVista> tDetalleVistas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tEntrada> tEntradas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tEntrada> tEntradas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tEntrada> tEntradas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tErrore> tErrores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tEvento> tEventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tFormaPagoCredito> tFormaPagoCreditoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tFormaPagoCredito> tFormaPagoCreditoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tHistoricoComisione> tHistoricoComisiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tHistoricoReparacione> tHistoricoReparaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMesaRegalo> tMesaRegalos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMesaRegalo> tMesaRegalos1 { get; set; }
        public virtual tMunicipio tMunicipio { get; set; }
        public virtual tNivelAcademico tNivelAcademico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNotasCredito> tNotasCreditoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNotasCredito> tNotasCreditoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNotasCredito> tNotasCreditoes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrigenCliente> tOrigenClientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrigenCliente> tOrigenClientes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPagoMes> tPagoMeses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPagoMes> tPagoMeses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPedido> tPedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPedido> tPedidos1 { get; set; }
        public virtual tPerfile tPerfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tProducto> tProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tProducto> tProductos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPromocione> tPromociones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPromocione> tPromociones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRecepcione> tRecepciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRecepcione> tRecepciones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRecepcione> tRecepciones2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tReparacione> tReparaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tReparacione> tReparaciones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tReparacione> tReparaciones2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tReporteComisionesEspeciale> tReporteComisionesEspeciales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tReporteVentasComisione> tReporteVentasComisiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRespaldoProductosSucursal> tRespaldoProductosSucursals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSalida> tSalidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSalida> tSalidas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSalida> tSalidas2 { get; set; }
        public virtual tSucursale tSucursale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tTicket> tTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tTicket> tTickets1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tTicket> tTickets2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tTicket> tTickets3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tTransferencia> tTransferencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tTransferencia> tTransferencias1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tTransferencia> tTransferencias2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tUsuarioEvento> tUsuarioEventoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tVentaMesaRegalo> tVentaMesaRegalos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tVentaMesaRegalo> tVentaMesaRegalos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tVenta> tVentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tVenta> tVentas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tVentasEnLinea> tVentasEnLineas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tVista> tVistas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tVista> tVistas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tVista> tVistas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSucursale> tSucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPreCotizacion> tPreCotizacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPreCotizacion> tPreCotizacions1 { get; set; }
    }
}
