//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tVentaMesaRegalo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tVentaMesaRegalo()
        {
            this.tDetalleVentaMesaRegalos = new HashSet<tDetalleVentaMesaRegalo>();
            this.tFormaPagoMesaRegalos = new HashSet<tFormaPagoMesaRegalo>();
        }
    
        public int idVenta { get; set; }
        public string Remision { get; set; }
        public Nullable<int> idUsuario1 { get; set; }
        public Nullable<int> idUsuario2 { get; set; }
        public Nullable<int> idClienteFisico { get; set; }
        public Nullable<int> idClienteMoral { get; set; }
        public Nullable<int> idDespachoReferencia { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> CantidadProductos { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<short> Estatus { get; set; }
        public Nullable<short> IVA { get; set; }
        public Nullable<short> Factura { get; set; }
        public string Comentarios { get; set; }
        public string NumeroFactura { get; set; }
        public Nullable<byte> TipoCliente { get; set; }
        public Nullable<int> idDespacho { get; set; }
        public Nullable<int> idMesaRegalos { get; set; }
    
        public virtual tClientesFisico tClientesFisico { get; set; }
        public virtual tClientesMorale tClientesMorale { get; set; }
        public virtual tDespacho tDespacho { get; set; }
        public virtual tDespacho tDespacho1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleVentaMesaRegalo> tDetalleVentaMesaRegalos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tFormaPagoMesaRegalo> tFormaPagoMesaRegalos { get; set; }
        public virtual tMesaRegalo tMesaRegalo { get; set; }
        public virtual tSucursale tSucursale { get; set; }
        public virtual tUsuario tUsuario { get; set; }
        public virtual tUsuario tUsuario1 { get; set; }
    }
}
