//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tVentasEnLinea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tVentasEnLinea()
        {
            this.tDetalleVentaEnLineas = new HashSet<tDetalleVentaEnLinea>();
        }
    
        public int idVenta { get; set; }
        public string Remision { get; set; }
        public Nullable<int> idCarrito { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idTipoEntrega { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> CantidadProductos { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> GastosEnvio { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string NumeroFactura { get; set; }
        public Nullable<int> Estatus { get; set; }
        public string IdOrdenOpenPay { get; set; }
        public string EstatusOpenPay { get; set; }
        public Nullable<bool> Facturado { get; set; }
        public Nullable<int> idVendedor { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public string EmpresaEnvio { get; set; }
        public string NumeroGuia { get; set; }
    
        public virtual tCarrito tCarrito { get; set; }
        public virtual tClientesTiendaVirtual tClientesTiendaVirtual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalleVentaEnLinea> tDetalleVentaEnLineas { get; set; }
        public virtual tSucursale tSucursale { get; set; }
        public virtual tUsuario tUsuario { get; set; }
    }
}
